/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package marketbeezup.vistas;

import marketbeezup.controladores.ImprimirControlador;
import marketbeezup.controladores.ModeloTablaAlbaranesImpr;
import java.awt.Insets;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import marketbeezup.modelos.Articulo;

/**
 *
 * @author Manolo
 */
public class ImprimirVista extends javax.swing.JDialog {

    ModeloTablaAlbaranesImpr modeloTablaAlbaranesImpr;
    DefaultListModel<String> modeloListaAgencias;

    /**
     * Creates new form Imprimir
     *
     * @param parent
     * @param modal
     */
    public ImprimirVista(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // Obtenemos el límite de pantalla
        Insets screenInsets = Toolkit.getDefaultToolkit().getScreenInsets(this.getGraphicsConfiguration());
        // Obtenemos la altura del borde inferior, que es la altura de la barra de tareas
        int taskHeight = screenInsets.bottom;
        // Fijamos el tamaño de la ventana al tamaño del escritorio menos la altura de la barra de tareas
        this.setSize(this.getToolkit().getScreenSize().width, this.getToolkit().getScreenSize().height - taskHeight);
        this.setTitle("Imprimir Albarán");
        selectorFecha.getJCalendar().setTodayButtonVisible(true);
        selectorFecha.getJCalendar().setNullDateButtonVisible(true);
        botonMarcar.setEnabled(false);
    }

    public void actualizarTabla(List<Articulo> articulos) {
        // Se muestran los pedidos en la tabla
        modeloTablaAlbaranesImpr = new ModeloTablaAlbaranesImpr(articulos);
        tablaAlbaranesImpr.setModel(modeloTablaAlbaranesImpr);
    }

    public void actualizarAgencias(List<Articulo> articulos) {
        List<String> agencias = new ArrayList<>();
        // Se obtiene la lista de agencias incluidas en los pedidos que se muestran en la tabla
        for (Articulo articulo : articulos) {
            if (articulo.getEnvio() != null) {
                if (!agencias.contains(articulo.getEnvio().getIdAgencia())) {
                    agencias.add(articulo.getEnvio().getIdAgencia());
                }
            }
        }
        // Se muestra el listado de agencias
        modeloListaAgencias = new DefaultListModel<>();
        modeloListaAgencias.addAll(agencias);
        listaAgencias.setModel(modeloListaAgencias);
    }

    public void habilitarMarcar(boolean habilitar) {
        botonMarcar.setEnabled(habilitar);
    }
    
    public void habilitarImprimir(boolean habilitar) {
        botonImprimir.setEnabled(habilitar);
    }

    public void setControlador(ImprimirControlador imprimirControlador) {
        botonImprimir.addActionListener(imprimirControlador);
        botonImprimir.setActionCommand("ImprimirAlbaranes");
        botonFiltrar.addActionListener(imprimirControlador);
        botonFiltrar.setActionCommand("FiltrarAlbaranes");
        botonLimpiar.addActionListener(imprimirControlador);
        botonLimpiar.setActionCommand("LimpiarFiltroAlbaranes");
        botonMarcar.addActionListener(imprimirControlador);
        botonMarcar.setActionCommand("MarcarImpresos");
        // selectorFecha.getDateEditor().adaddActionListener("FiltrarAlbaranes");
    }

    public List<String> getAgenciasSeleccionadas() {
        return listaAgencias.getSelectedValuesList();
    }

    public void setAgenciasSeleccionadas(String agenciaSeleccionada) {
        listaAgencias.setSelectedValue(agenciaSeleccionada, true);
    }

    public java.sql.Date getFechaSeleccionada() {
        if (selectorFecha.getDate() == null) {
            return null;
        } else {
            return new java.sql.Date(selectorFecha.getDate().getTime());
        }
    }

    public void setFechaSeleccionada(java.sql.Date fecha) {
        if (fecha != null) {
            selectorFecha.setDate(new java.util.Date(fecha.getTime()));
        } else {
            selectorFecha.setDate(null);
        }
    }

    public String getIdPedido() {
        if (textoIdPedido.getText().isBlank()) {
            return null;
        } else {
            return textoIdPedido.getText();
        }
    }

    public void setIdPedido(String idPedido) {
        textoIdPedido.setText(idPedido);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaAgencias = new javax.swing.JList<>();
        selectorFecha = new com.toedter.calendar.JDateChooser();
        textoIdPedido = new javax.swing.JTextField();
        botonImprimir = new javax.swing.JButton();
        botonFiltrar = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        botonMarcar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAlbaranesImpr = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 132));
        jPanel1.setMinimumSize(new java.awt.Dimension(640, 132));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 132));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Fecha");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Id Pedido");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agencias", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        listaAgencias.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(listaAgencias);

        selectorFecha.setDateFormatString("dd-MM-yy");
        selectorFecha.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        selectorFecha.setMaximumSize(new java.awt.Dimension(150, 23));
        selectorFecha.setMinimumSize(new java.awt.Dimension(150, 23));
        selectorFecha.setPreferredSize(new java.awt.Dimension(150, 23));

        textoIdPedido.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textoIdPedido.setMaximumSize(new java.awt.Dimension(219, 23));
        textoIdPedido.setMinimumSize(new java.awt.Dimension(219, 23));
        textoIdPedido.setPreferredSize(new java.awt.Dimension(219, 23));

        botonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marketbeezup/imagenes/Imprimir32.png"))); // NOI18N
        botonImprimir.setText("Imprimir");
        botonImprimir.setToolTipText("Imprimir Albaranes");
        botonImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        botonFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marketbeezup/imagenes/Filtrar32.png"))); // NOI18N
        botonFiltrar.setText("Filtrar");
        botonFiltrar.setToolTipText("Filtrar");
        botonFiltrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonFiltrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        botonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marketbeezup/imagenes/Limipiar32.png"))); // NOI18N
        botonLimpiar.setText("Limpiar");
        botonLimpiar.setToolTipText("Limpiar Filtro");
        botonLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonLimpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marketbeezup/imagenes/Cancelar32.png"))); // NOI18N
        botonCancelar.setText("Salir");
        botonCancelar.setToolTipText("Salir");
        botonCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        botonMarcar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marketbeezup/imagenes/Check.png"))); // NOI18N
        botonMarcar.setText("Marcar");
        botonMarcar.setToolTipText("Marcar como Impreso");
        botonMarcar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonMarcar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(selectorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoIdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonImprimir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonMarcar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonFiltrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCancelar)))
                .addGap(168, 168, 168))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonCancelar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(selectorFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(textoIdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(botonFiltrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(botonImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(botonMarcar))
                                    .addComponent(botonLimpiar, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(1, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        tablaAlbaranesImpr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaAlbaranesImpr.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(tablaAlbaranesImpr);

        getContentPane().add(jScrollPane2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImprimirVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImprimirVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImprimirVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImprimirVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ImprimirVista dialog = new ImprimirVista(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonFiltrar;
    private javax.swing.JButton botonImprimir;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JButton botonMarcar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaAgencias;
    private com.toedter.calendar.JDateChooser selectorFecha;
    private javax.swing.JTable tablaAlbaranesImpr;
    private javax.swing.JTextField textoIdPedido;
    // End of variables declaration//GEN-END:variables
}
